apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudoku-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sudoku
  template:
    metadata:
      labels:
        app: sudoku
    spec:
      containers:
        - name: sudoku
          image: sudoku-devops:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sudoku-svc
spec:
  type: NodePort
  selector:
    app: sudoku
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
